import React from 'react';
import { CategoryKey, Locale } from './types';
import { FourPillarsIcon, PersonalityIcon, OverallIcon, LifeStagesIcon, WealthIcon, CareerIcon, LoveIcon, HealthIcon } from './components/icons';

// UI Translations
export const translations: Record<Locale, Record<string, string>> = {
  ko: {
    // Header
    appTitle: 'AI 운세 분석',
    startNewAnalysis: '새 분석 시작',
    language: '언어',
    
    // InputForm
    inputTitle: '분석 정보 입력',
    inputDescription: '정확한 분석을 위해 정보를 입력해주세요.\n얼굴 사진은 선택사항이며, 관상학적 참고 자료로만 활용됩니다.',
    nameLabel: '이름 (필수)',
    namePlaceholder: '홍길동',
    dobLabel: '생년월일 (필수)',
    tobLabel: '태어난 시간 (선택)',
    photoLabel: '얼굴 사진 (선택)',
    photoPlaceholder: '파일을 선택하거나 드래그 앤 드롭하세요',
    startAnalysis: '분석 시작하기',
    analyzing: '분석 중...',

    // GenerationProgress
    progressTitle: '운세를 분석하고 있습니다...',
    progressDescription: '잠시만 기다려 주세요. 우주의 기운을 모으는 중입니다.',
    progressDescriptionErrorInProgress: '분석 중 {count}개 항목에서 오류가 발생했습니다. 나머지를 계속 진행합니다.',
    progressDescriptionErrorComplete: '분석이 완료되었지만, {count}개 항목에서 오류가 발생했습니다.',
    pendingStatusShort: '대기중',
    analyzingStatusShort: '분석중',
    completedStatusShort: '완료',
    failedStatusShort: '실패',
    pendingMessage: '{categoryName} 분석 대기 중...',
    analyzingMessage: '{categoryName} 분석 중...',
    completedMessage: '{categoryName} 분석 완료',
    
    // ResultsDisplay
    resultsTitle: '님의 운세 분석 결과',
    resultsDescription: '카드를 뒤집어 요약을 확인하고, 클릭하여 상세 내용을 보세요.',

    // FortuneCard
    viewDetails: '더 보기...',

    // DetailModal
    summary: '요약',
    share: '결과 공유',
    close: '닫기',
    previous: '이전',
    next: '다음',
    shareSuccess: '결과가 클립보드에 복사되었습니다!',
    shareError: '복사에 실패했습니다.',
    shareText: '{categoryName} 운세 분석\n\n요약: {summary}\n\n*AI 운세 분석으로 생성된 결과입니다.*',
  },
  en: {
    // Header
    appTitle: 'AI Fortune Analysis',
    startNewAnalysis: 'New Analysis',
    language: 'Language',
    
    // InputForm
    inputTitle: 'Enter Your Information',
    inputDescription: 'Please enter your information for an accurate analysis.\nA face photo is optional and used only for physiognomic reference.',
    nameLabel: 'Name (Required)',
    namePlaceholder: 'John Doe',
    dobLabel: 'Date of Birth (Required)',
    tobLabel: 'Time of Birth (Optional)',
    photoLabel: 'Face Photo (Optional)',
    photoPlaceholder: 'Select a file or drag and drop',
    startAnalysis: 'Start Analysis',
    analyzing: 'Analyzing...',

    // GenerationProgress
    progressTitle: 'Analyzing your fortune...',
    progressDescription: 'Please wait a moment. We are gathering cosmic energy.',
    progressDescriptionErrorInProgress: 'An error occurred in {count} item(s). Continuing with the rest.',
    progressDescriptionErrorComplete: 'Analysis complete, but errors occurred in {count} item(s).',
    pendingStatusShort: 'Pending',
    analyzingStatusShort: 'Analyzing',
    completedStatusShort: 'Completed',
    failedStatusShort: 'Failed',
    pendingMessage: '{categoryName} analysis pending...',
    analyzingMessage: '{categoryName} analyzing...',
    completedMessage: '{categoryName} analysis complete',

    // ResultsDisplay
    resultsTitle: "'s Fortune Analysis Results",
    resultsDescription: 'Flip the cards to see the summary, and click to view details.',

    // FortuneCard
    viewDetails: 'View Details...',

    // DetailModal
    summary: 'Summary',
    share: 'Share Results',
    close: 'Close',
    previous: 'Previous',
    next: 'Next',
    shareSuccess: 'Results copied to clipboard!',
    shareError: 'Failed to copy.',
    shareText: '{categoryName} Fortune Analysis\n\nSummary: {summary}\n\n*Result generated by AI Fortune Analysis.*',
  },
  zh: {
    // Header
    appTitle: 'AI 运势分析',
    startNewAnalysis: '开始新分析',
    language: '语言',

    // InputForm
    inputTitle: '输入您的信息',
    inputDescription: '请输入您的信息以进行准确分析。\n脸部照片是可选的，仅用作面相参考。',
    nameLabel: '姓名 (必填)',
    namePlaceholder: '张三',
    dobLabel: '出生日期 (必填)',
    tobLabel: '出生时间 (可选)',
    photoLabel: '脸部照片 (可选)',
    photoPlaceholder: '选择文件或拖放',
    startAnalysis: '开始分析',
    analyzing: '分析中...',

    // GenerationProgress
    progressTitle: '正在分析您的运势...',
    progressDescription: '请稍候。我们正在聚集宇宙的能量。',
    progressDescriptionErrorInProgress: '在 {count} 个项目中发生错误。正在继续处理其余项目。',
    progressDescriptionErrorComplete: '分析完成，但在 {count} 个项目中发生了错误。',
    pendingStatusShort: '等待中',
    analyzingStatusShort: '分析中',
    completedStatusShort: '完成',
    failedStatusShort: '失败',
    pendingMessage: '{categoryName} 分析等待中...',
    analyzingMessage: '{categoryName} 分析中...',
    completedMessage: '{categoryName} 分析完成',

    // ResultsDisplay
    resultsTitle: '的运势分析结果',
    resultsDescription: '翻转卡片查看摘要，点击查看详情。',

    // FortuneCard
    viewDetails: '查看详情...',

    // DetailModal
    summary: '摘要',
    share: '分享结果',
    close: '关闭',
    previous: '上一个',
    next: '下一个',
    shareSuccess: '结果已复制到剪贴板！',
    shareError: '复制失败。',
    shareText: '{categoryName} 运势分析\n\n摘要: {summary}\n\n*结果由 AI 运势分析生成。*',
  },
};


// Category Definitions
// Fix: Store icon components directly instead of rendered JSX elements.
// This avoids potential issues with JSX syntax in a .ts file.
const ICONS: Record<CategoryKey, React.FC> = {
    four_pillars: FourPillarsIcon,
    personality: PersonalityIcon,
    overall: OverallIcon,
    life_stages: LifeStagesIcon,
    wealth: WealthIcon,
    career: CareerIcon,
    love: LoveIcon,
    health: HealthIcon,
};

const CATEGORY_NAMES: Record<Locale, Record<CategoryKey, string>> = {
    ko: {
      four_pillars: '사주팔자 및 오행',
      personality: '타고난 성격 및 기질',
      overall: '인생 총운',
      life_stages: '초년, 중년, 말년운',
      wealth: '재물운',
      career: '직업운',
      love: '연애 및 결혼운',
      health: '건강운',
    },
    en: {
      four_pillars: 'Four Pillars & Five Elements',
      personality: 'Innate Personality & Temperament',
      overall: 'Overall Life Fortune',
      life_stages: 'Early, Middle, and Late Life Fortune',
      wealth: 'Wealth Fortune',
      career: 'Career Fortune',
      love: 'Love & Marriage Fortune',
      health: 'Health Fortune',
    },
    zh: {
      four_pillars: '生辰八字与五行',
      personality: '天赋性格与气质',
      overall: '人生总运',
      life_stages: '初年、中年、晚年运',
      wealth: '财运',
      career: '事业运',
      love: '恋爱与婚姻运',
      health: '健康运',
    },
};

export const getCategories = (locale: Locale): Record<CategoryKey, { name: string; icon: JSX.Element }> => {
    const names = CATEGORY_NAMES[locale];
    return (Object.keys(names) as CategoryKey[]).reduce((acc, key) => {
        // Fix: Create the element dynamically when the function is called.
        // Using React.createElement is safer in a .ts file than JSX syntax.
        acc[key] = { name: names[key], icon: React.createElement(ICONS[key]) };
        return acc;
    }, {} as Record<CategoryKey, { name: string; icon: JSX.Element }>);
};


// Prompt System Instructions
export const getPromptSystemInstruction = (locale: Locale): string => {
    const instructions: Record<Locale, string> = {
        ko: `당신은 전통적인 동양 운세 개념을 현대적인 관점에서 명확하고 투명하게 해석하는 운세 분석 전문가입니다. 사용자의 정보를 바탕으로 각 운세 카테고리에 대해 상세히 분석하고, 그 근거와 한계점을 솔직하게 명시해야 합니다. 모든 답변은 한국어로 작성해주세요. 답변은 항상 요청된 JSON 형식으로만 제공해야 합니다.`,
        en: `You are an expert fortune analysis professional who interprets traditional Eastern fortune-telling concepts from a modern, clear, and transparent perspective. Based on the user's information, you must analyze each fortune category in detail, and honestly state the basis for your analysis and its limitations. All responses must be written in English. You must always provide the answer only in the requested JSON format.`,
        zh: `您是一位专业的运势分析专家，能以现代、清晰、透明的视角解读传统的东方命理概念。您必须根据用户提供的信息，详细分析每个运势类别，并坦诚地说明分析的依据及其局限性。所有回答都必须用中文书写。您必须始终只以请求的JSON格式提供答案。`,
    };
    return instructions[locale];
};